name: Publish docs

on:
  release:
    types: ["created"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Build and publish
        run: mkdocs gh-deploy --force
